application:
  name: pacifica-uploader
  project: pacifica-uploader
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
  - name: main
    routes:
      - application_name: pacifica-uploader
        paths:
          - /*
